spring:
  application:
    name: server
  security:
    user:
      name: root
      password: root

eureka:
  instance:
    prefer-ip-address: false
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:root@peer1:8761/eureka/,http://root:root@peer2:8762/eureka/,http://root:root@peer3:8763/eureka/

---
spring:
  profiles: peer1

server:
  port: 8761

eureka:
  instance:
    hostname: server1
---
spring:
  profiles: peer2

server:
    port: 8762

eureka:
    instance:
      hostname: server2
---
spring:
  profiles: peer3

server:
  port: 8763

eureka:
  instance:
    hostname: server3
